default:
  top_n: 1000
  plot: true
  log_normal_regression: true
  regressor_lower_bound: 2
  regressor_upper_bound: 2
  target_lower_bound: 1
  target_upper_bound: 2
  target: quantity
  write_to_db: true
  regressor: avg_price
  days_before: 365