default:
  name: 'OptunaRandomSearch'
  price_lower_bound: 0.9
  price_upper_bound: 1.1
  forecast_stock_level: 120
  opt_stock_level: 20
  stockout_penalty: 5
  n_trials: 50
  n_jobs: 1
  write_to_db: true

