default:
  training:
    target_col: 'click_rate'
    target_01: true
    data_split:
      test_size: 0.3
      test_val_size: 0.5
      random_seed_split: null
    baseline_model:
      baseline_name: sklearn.linear_model.LinearRegression  # or 'sklearn.linear_model.Ridge', 'xgboost.XGBRegressor', etc.
      baseline_params: # Parameters for the base model
        fit_intercept: True
    torch_mlp:
      device: cpu
      batch_size: 256
      torch_random_seed: null
      epochs: 50
      mlp_parameters:
        output_size: 1
        hidden_layer_sizes:
          - 16  # Only one Hidden Layer
        output_activation: sigmoid  # identity for linear output
        activation: relu  # options (relu, leaky_relu, sigmoid, tanh, identity)
        dropout_rate: 0.1  # Remove dropout
        norm_batch:
          use_norm_batch: True
          parameters:
            momentum: 0.1
            eps: 1e-5
        use_attention: True
      torch_optimizer:
        criterion: MSELoss # L1Loss for MAE, MSELoss, BCELoss, etc.
        lr_scheduler:
          use_scheduler: True
          parameters:
            patience: 3  # Increased patience
            factor: 0.5
            min_lr: 1e-6
        Adam:
          lr: 0.001
          betas:
            - 0.8
            - 0.999
          eps: 1e-8
          weight_decay: 1e-15
